name: updater

on:
  schedule:
    - cron: '* */2 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

      # Runs a single command using the runners shell
    - name: парсинг прокси
      run: |
        pip install telebot
        pip install pytelegrambotapi
        curl https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt > proxy.txt
        python3 main.py
      env:
        CI: true

        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
